#' CVA 2D Shape Change
#' 
#' Visualize Shape change in two dimenions of Morpho object.class 'CVA'
#' 
#' @param CVA object of class CVA generated by Morpho::CVA
#' @param variate The canonical variate to be visualized (default = 1)
#' @param scale A scaling factor to emphasize shape change (default = 5)
#' 
#' @export
#' 
#' @return Plots the mean landmark configuration of a CVA an vectors representing the shape change along a given variate, by a given scale
#' 
#' 
CV.2D.shape <- function(CVA, variate = 1, scale = 5){
  #Function to visualize CVA shape changes of landmarks 
  #where CVA is an object of class 'CVA' from Morpho
  
  ref <- Morpho::CVA$Grandm
  target <- scale*matrix(CVA$CVvis[,variate], nrow(CVA$Grandm), ncol(CVA$Grandm)) + CVA$Grandm
  
  plot(ref, asp=1, xlab = "", ylab = "", axes = F)
  for (i in 1:nrow(ref)){
    lines(rbind(ref[i,], target[i,]), col = "red")
  }
  
}


#####and 3D plot#####
####Note: scale makes spheres too big, add an inverse scaling factor to those plots.
####Also, open3d means multi plots are impossible

CV.3D.shape <- function(CVA, variate = 1, scale = 5, links = NULL){
  ref <- Morpho::CVA$Grandm
  target <- scale*matrix(CVA$CVvis[,variate], nrow(CVA$Grandm), ncol(CVA$Grandm)) + CVA$Grandm
  r <- range(ref[,1])*1.1
  
  open3d()
  rgl.clear()
  plot3d(ref, xlim = r, ylim = r, zlim = r, axes = F, type = "p", size = abs(scale)*1.5)
  
  for (i in 1:nrow(ref)){
    lines3d(rbind(ref[i,],target[i,]), col = "red", lwd = 1.5)
  }
  
}
